# Generated by Django 5.2 on 2025-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_song_coverimage_song_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favourited',
            field=models.BooleanField(default=False),
        ),
    ]
