# Generated by Django 5.2 on 2025-05-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_song_favourited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='favourited',
        ),
    ]
