# Generated by Django 5.1.3 on 2025-06-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.artist'),
        ),
    ]
