# Generated by Django 5.2 on 2025-05-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_song_favourited'),
        ('user', '0002_sounduser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sounduser',
            name='favourite_songs',
            field=models.ManyToManyField(blank=True, related_name='favourited_by', to='main.song'),
        ),
    ]
